LeadApp/Models/Task.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskAssignees = new HashSet<TaskAssignee>();
            this.TaskReferences = new HashSet<TaskReference>();
            this.TaskResponses = new HashSet<TaskRespons>();
        }
    
        public System.Guid TaskID { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
        public bool isClosed { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ActivityStatus ActivityStatus { get; set; }
        public virtual AppUser AppUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignee> TaskAssignees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskReference> TaskReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskRespons> TaskResponses { get; set; }
    }
}

LeadApp/Models/TaskModel/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadApp.Models
{
	[MetadataType(typeof(TaskMetaData))]
	public partial class Task
	{

		[DataType(DataType.DateTime), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy hh:mm tt}")]
		public System.DateTime LastReplyDate { get; set; }

	}

	public class TaskMetaData
	{

		[DataType(DataType.DateTime), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy hh:mm tt}")]
		public System.DateTime CreatedDate { get; set; }

		[AllowHtml]
		public string Description { get; set; }
	}

	[MetadataType(typeof(TaskResponseMetaData))]
	public partial class TaskRespons
	{
	}

	public class TaskResponseMetaData
	{
		[DataType(DataType.DateTime), DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy hh:mm tt}")]
		public System.DateTime ResponseDate { get; set; }

		[AllowHtml]
		public string Response { get; set; }
	}


}

LeadApp/Controllers/TaskController.cs
using LeadApp.Helpers;
using LeadApp.Models;
using LeadApp.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace LeadApp.Controllers {
	[Restricted]
	public class TaskController: Controller {
		TaskServices _serv = new TaskServices();
		UserService _servUser = new UserService();
		private string error = string.Empty;


        public ActionResult Index(string q)
        {
			IEnumerable<Task> _data = _serv.GetAllTasks();

            if (!string.IsNullOrEmpty(q))
				return View(_data.Where(e => e.Title.Contains(q) || e.Description.Contains(q)));
            else
				return View(_data);			
		}






		public ActionResult Create() {
			ViewBag.AssigneeUserID = new MultiSelectList(_servUser.GetEmployees(), "UserId", "ContactName");
			ViewBag.StatusID = new SelectList(_serv.GetStatus(), "StatusID", "StatusName");
			return View();
		}

		[HttpPost]
		public ActionResult Create(Task Data, List<int> AssigneeUserID) {
			string error = "";

            if (AssigneeUserID.Count == 0)
                ModelState.AddModelError("AssigneeUserID", "You must assign atleast one user");


			if (ModelState.IsValid) {
					bool isCreate = _serv.AddTask(Data, AssigneeUserID, out error);
					TempData["AlertCSS"] = isCreate ? "alert success" : "alert error";

					if (!isCreate)
						ModelState.AddModelError("", error);
					else
						TempData["OutputMessage"] = "Task Successfully Created";

					if (ModelState.IsValid)
						return RedirectToAction("Index");
			}

			ViewBag.AssigneeUserID = new MultiSelectList(_servUser.GetEmployees(), "UserId", "ContactName", AssigneeUserID);
			ViewBag.StatusID = new SelectList(_serv.GetStatus(), "StatusID", "StatusName", Data.StatusID);

			return View(Data);
		}







		public ActionResult Edit(Guid? id)
		{
			if (!HelperMethods.IsGUID(id))
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

			Task _data = _serv.GetTask(id.ConvertToGUID());
			if (_data == null)
				return HttpNotFound();

			if (_data.CreatedBy != Auth.UserID)
			{
				TempData["AlertCSS"] = "alert error";
				TempData["OutputMessage"] = "You can edit your own task only";
				return RedirectToAction("Index");
			}

			ViewBag.AssigneeUserID = new MultiSelectList(_servUser.GetEmployees(), "UserId", "ContactName", _data.TaskAssignees.Select(e => e.AssigneeUserID));
			ViewBag.StatusID = new SelectList(_serv.GetStatus(), "StatusID", "StatusName", _data.StatusID);


			return View(_data);
		}

		[HttpPost]
		public ActionResult Edit(Task Data, List<int> AssigneeUserID, string Mode)
		{
			

			if (AssigneeUserID.Count == 0)
				ModelState.AddModelError("AssigneeUserID", "You must assign atleast one user");


			if (ModelState.IsValid)
			{
				bool isSuccess = _serv.Edit(Data, AssigneeUserID, out error);
				TempData["AlertCSS"] = isSuccess ? "alert success" : "alert error";

				if (!isSuccess)
					ModelState.AddModelError("", error);
				else
					TempData["OutputMessage"] = "Task Successfully Edited";

				if (ModelState.IsValid)
					return RedirectToAction("Index");
			}

			ViewBag.AssigneeUserID = new MultiSelectList(_servUser.GetEmployees(), "UserId", "ContactName", AssigneeUserID);
			ViewBag.StatusID = new SelectList(_serv.GetStatus(), "StatusID", "StatusName", Data.StatusID);

			return View(Data);
		}








		public ActionResult Detail(Guid id) {
			Task Data = _serv.GetTask(id);
			ViewBag.TaskStatus = new SelectList(_serv.GetStatus(), "StatusID", "StatusName", Data.StatusID);
			ViewBag.StatusID = new SelectList(_serv.GetStatus(), "StatusID", "StatusName");
			return View(Data);
		}

		[HttpPost]
        public ActionResult Detail(TaskRespons Data)
        {
			ViewBag.TaskStatus = new SelectList(_serv.GetStatus(), "StatusID", "StatusName", Data.StatusID);
			ViewBag.StatusID = new SelectList(_serv.GetStatus(), "StatusID", "StatusName");


			if (ModelState.IsValid) {

				bool isCreate = _serv.AddReply(Data, out error);
				TempData["AlertCSS"] = isCreate ? "alert success" : "alert error";

				if (!isCreate)
					ModelState.AddModelError("", error);
				else
					TempData["OutputMessage"] = "Task Reply Successfully Submitted";

				if (ModelState.IsValid)
					return RedirectToAction("Detail", new { id = Data.TaskID });
			}


			return View(Data);
		}



		public ActionResult _TaskSummary(Guid id) {
			return View(_serv.GetAllTaskReply(id));
		}


		public ActionResult Delete(Guid id) {
			//ViewData["ID"] = id;
			if (ModelState.IsValid) {

				bool isCreate = _serv.DeleteTask(id, out error);
				TempData["AlertCSS"] = isCreate ? "alert success" : "alert error";

				if (!isCreate)
					ModelState.AddModelError("", error);
				else
					TempData["OutputMessage"] = "Task  Successfully deleted";

				if (ModelState.IsValid) {
					return RedirectToAction("Index");
				}

			}
			return RedirectToAction("Index");

		}



		public ActionResult Closed(Guid id) {

			bool isSuccess = _serv.CloseTask(id, out error);
			TempData["AlertCSS"] = isSuccess ? "alert success" : "alert error";

			if (!isSuccess)
				ModelState.AddModelError("", error);
			else
				TempData["OutputMessage"] = "Task Closed Successfully!";

			return RedirectToAction("Detail", new { id = id });

		}

		[HttpPost]
		public ActionResult ChangeStatus(Guid TaskID, string status) {
			bool isSuccess = false;
			if (status == "Completed & Close")
				isSuccess = _serv.CloseTask(TaskID, out error);
			else
				isSuccess = _serv.ChangeStatus(TaskID, status, out error);

			TempData["AlertCSS"] = isSuccess ? "alert success" : "alert error";	
			if (!isSuccess)
				ModelState.AddModelError("", error);
			else
				TempData["OutputMessage"] = "Task Status Updated Successfully";

			return RedirectToAction("Detail", new { id = TaskID });

		}


	}
}

LeadApp/Views/Task/Create.cshtml
@model LeadApp.Models.Task
@{
	ViewBag.Title = "New Task";
}


<script type="text/javascript">
	$(document).ready(function () {
		$('#DateDue').datetimepicker({ format: 'd M Y h:i A' });
		$('#Description').ckeditor();
	});
</script>

@using (Html.BeginForm()) {
	@Html.AntiForgeryToken()
	<table>
		<tr>
			<td>Subject</td>
			<td>@Html.EditorFor(m => m.Title, new { htmlAttributes = new { size = 100 } })  @Html.ValidationMessageFor(model => model.Title)</td>
		</tr>
		<tr>
			<td>Assign to</td>
			<td>@Html.ListBox("AssigneeUserID") @Html.ValidationMessageFor(model => model.TaskAssignees) </td>
		</tr>
		<tr>
			<td>Due Date</td>
			<td>@Html.EditorFor(m => m.DateDue) <span class="small-info">Leave blank if no due date</span> @Html.ValidationMessageFor(model => model.DateDue) </td>
		</tr>
		<tr>
			<td>Task Status</td>
			<td>@Html.DropDownList("StatusID")  </td>
		</tr>
		<tr>
			<td colspan="2">@Html.TextAreaFor(m => m.Description) @Html.ValidationMessageFor(model => model.Description)</td>
		</tr>
	</table>
	<div>
		<input type="submit" value="Save" class="btn btn-default" />
	</div>
}


LeadApp/Views/Task/Detail.cshtml
@model LeadApp.Models.Task
@{
	ViewBag.Title = "Task Detail";
	LeadApp.Models.TaskRespons AddResponse = new LeadApp.Models.TaskRespons();
	AddResponse.TaskID = Model.TaskID;


	var AuthorThumbImg = @Model.AppUser.AppUserMetas.Where(e => e.MetaKey == "Thumbnail-Original").Select(e => e.MetaValue).FirstOrDefault();
	string AuthorThumbnail = WebConstants.Default_UserThumbURL;
	if (AuthorThumbImg != null)
		AuthorThumbnail = WebConstants.UserProfileThumbURL + "thb32-" + AuthorThumbImg;
}

@if (Model.CreatedBy == Auth.UserID && Model.isClosed != true)
{
	@section KeyButtons {
		@using (Html.BeginForm("ChangeStatus", "Task"))
		{
			@Html.HiddenFor(m => m.TaskID)
			<input type="submit" name="status" value="In Progress" class="btn small" />
			<input type="submit" name="status" value="Postponed" class="btn small" />
			<input type="submit" name="status" value="Completed" class="btn small" />
			<input type="submit" name="status" value="Completed & Close" class="btn small" />
			<input type="submit" name="status" value="Cancelled" class="btn small red" />
		}
	}
}



<h2 class="heading">@Html.DisplayFor(m => m.Title)</h2>
<div class="row">
	<div class="col-3"><strong>Assigned By:</strong> <a href="/User/ViewProfile?id=@Model.CreatedBy"><span class="profile-icon"><img width="24" height="24" src="@AuthorThumbnail" alt="" /></span> @Html.DisplayFor(m => m.AppUser.AppEmployees.First().ContactName)</a></div>
	<div class="col-3"><strong>Status:</strong> @Html.DisplayFor(m => m.ActivityStatus.StatusName)</div>
	<div class="col-3"><strong>Due Date:</strong> @Html.DisplayFor(m => m.DateDue)</div>

	@if (Model.TaskAssignees.Count() > 0)
	{
		<div class="col-3">
			<strong>Assignees:</strong><br />
			@foreach (var u in Model.TaskAssignees)
			{

				var ThumbImg = @u.AppUser.AppUserMetas.Where(e => e.MetaKey == "Thumbnail-Original").Select(e => e.MetaValue).FirstOrDefault();
				var Assignee = u.AppUser.AppEmployees.FirstOrDefault();

				string AssigneeName = Assignee != null ? Assignee.ContactName : "-";
				string Thumbnail = (ThumbImg != null) ? WebConstants.UserProfileThumbURL + "thb32-" + ThumbImg : WebConstants.Default_UserThumbURL;

				<div><a href="/User/ViewProfile?id=@u.AssigneeUserID"><span class="profile-icon"><img width="24" height="24" src="@Thumbnail" alt="" /></span> @AssigneeName</a> </div>
			}
		</div>
	}
</div>
<div class="row">
	@Html.Raw(HttpUtility.HtmlDecode(Model.Description))
</div>
<br />
<br />
<h3 class="expander heading">Responses</h3>
<div class="row expandable task-summary-cont">
	@{Html.RenderAction("_TaskSummary", new { id = Model.TaskID }); }
</div>






@if (Model.isClosed != true)
{
	@Html.Partial("_Reply", AddResponse)
}
else
{
	<div class="row">
		<div class="alert info">Task is closed, further responses cannot be submitted!</div>
	</div>
}


@ActivityLogHelper.Show("Task", true, Model.TaskID)


LeadApp/Views/Task/Edit.cshtml
@model LeadApp.Models.Task
@{
	ViewBag.Title = "New Task";
}


<script type="text/javascript">
	$(document).ready(function () {
		$('#DateDue').datetimepicker({ format: 'd M Y h:i A' });
		$('#Description').ckeditor();
	});
</script>

@using (Html.BeginForm()) {
	@Html.AntiForgeryToken()
	@Html.HiddenFor(m => m.TaskID)
	<table>
		<tr>
			<td>Subject</td>
			<td>@Html.EditorFor(m => m.Title, new { htmlAttributes = new { size = 100 } }) @Html.ValidationMessageFor(model => model.Title) </td>
		</tr>
		<tr>
			<td>Assign to</td>
			<td>@Html.ListBox("AssigneeUserID") @Html.ValidationMessageFor(model => model.TaskAssignees) </td>
		</tr>
		<tr>
			<td>Due Date</td>
			<td>@Html.EditorFor(m => m.DateDue) <span class="small-info">Leave blank if no due date</span> @Html.ValidationMessageFor(model => model.DateDue)</td>
		</tr>
		<tr>
			<td>Task Status</td>
			<td>@Html.DropDownList("StatusID")  </td>
		</tr>
		<tr>
			<td colspan="2">@Html.TextAreaFor(m => m.Description) @Html.ValidationMessageFor(model => model.Description)</td>
		</tr>
	</table>
	<div>
		<input type="submit" value="Save" class="btn btn-default" />
	</div>
}


LeadApp/Views/Task/Index.cshtml
@model IEnumerable<LeadApp.Models.Task>
@{
	ViewBag.Title = "To-Do Tasks";
	var grid = new WebGrid(Model, canPage : true, rowsPerPage : WebConstants.PagingSize, selectionFieldName : "selectedRow", ajaxUpdateContainerId : "grid-content");
	grid.Pager(WebGridPagerModes.NextPrevious);
}
@section SearchForm {
}
@section TopButtons {
	@Html.ActionLink("New Task", "Create", null, new { @class = "btn" })
}


<div id="grid-content">
	@if (Model.Count() > 0) {
		@grid.GetHtml(tableStyle : "content-table grid",
			headerStyle : "grid-header",
			footerStyle : "grid-footer",
			alternatingRowStyle : "alt-row",
			selectedRowStyle : "select-row",
			mode : WebGridPagerModes.All,
			firstText : "<< First",
			previousText : "Prev",
			nextText : "Next",
			lastText : "Last >>",

				columns : grid.Columns(
				grid.Column("Title", "Subject"),
				grid.Column("ActivityStatus.StatusName", "Status"),
				grid.Column(header: "Assign By", format: (item) =>
					 {
						 return (CommonHelpers.AssignBy(item.AppUser.AppEmployees));
					 }
				 ), 
				 grid.Column(header: "Assignees", format: (item) =>
				 {
					return (CommonHelpers.Assignees(item.TaskAssignees));
				}
			),
				grid.Column(header : "Close", format : (item) => {
					if (item.isClosed)
						return Html.Raw(string.Format("<text><img src=\"{0}\" alt=\"Close\"/></text>", Url.Content("~/Content/images/success.png")));
					else
						return Html.Raw(string.Format("<text>-</text>"));
				}
			),
				grid.Column("DateDue", "Due Date", format : (item) => (HelperMethods.FormatDateTime(item.DateDue))),
				grid.Column("", header : "Action", style : "grid-actions", format : @<text>
		@Html.ActionLink("View", "Detail", new { id = item.TaskID }, new { @class = "grid-view" })
		@if (Auth.UserID == item.CreatedBy && !item.isClosed) {
			@Html.ActionLink("Edit", "Edit", new { id = item.TaskID }, new { @class = "grid-edit" })         	
			@Html.ActionLink("Delete", "Delete", new { id = item.TaskID }, new { @class = "grid-delete delete-link" })
		}
		</text>)
 ))
	} else {
		<div class="alert info">No Record Found</div>
	}

</div>

@DeleteHelper.Show()

LeadApp/Views/Task/_Reply.cshtml
@model LeadApp.Models.TaskRespons

<script type="text/javascript">
	$(document).ready(function () {
		$('#Response').ckeditor();
	});
</script>

<br />
<br />
<h3 class="expander heading">Your Reply</h3>
<div class="expandable">
	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()
		@Html.HiddenFor(m => m.TaskID)

		<div class="row">@Html.TextAreaFor(m => m.Response)</div>
		<div class="row">
			<div class="col-2">@Html.DropDownList("StatusID") </div>
			<div class="col-2">
				<input type="submit" value="Submit" class="btn btn-default" />
			</div>
		</div>
	}
</div>

LeadApp/Views/Task/_TaskSummary.cshtml
@model IEnumerable<LeadApp.Models.TaskRespons>
@{
	ViewBag.Title = "Task History";
	Layout = null;
}

@{
	int i = 1;
	foreach (var item in Model)
	{
		string AltRow = (i % 2 != 0) ? "" : " alt";
		var ThumbImg = item.AppUser.AppUserMetas.Where(e => e.MetaKey == "Thumbnail-Original").Select(e => e.MetaValue).FirstOrDefault();
		var Author = item.AppUser.AppEmployees.FirstOrDefault();

		string AuthorName = Author != null ? Author.ContactName : "-";
		string Thumbnail = WebConstants.Default_UserThumbURL;
		if (ThumbImg != null)
		{
			Thumbnail = WebConstants.UserProfileThumbURL + "thb32-" + ThumbImg;
		}
		<div class="row @AltRow">

			<div class="col section">
				<div class="col-1 summary-number">
					<h4 class="heading">Reply <span>#@i</span></h4>
				</div>
				<div class="col-11 summary-detail">
					<div class="row">
						<div class="col">
							<div class="col-4"><strong>Submitted By:</strong> <span class="user-id"><a href="/User/ViewProfile?id=@item.SubmitUserID"><span class="profile-icon"><img width="24" height="24" src="@Thumbnail" alt="" /></span> @AuthorName</a></span></div>
							<div class="col-4"><strong>Status:</strong> <span class="@Html.DisplayFor(m => item.ActivityStatus.StatusName)">@Html.DisplayFor(m => item.ActivityStatus.StatusName)</span> </div>
							<div class="col-4"><strong>Response Date:</strong> <span class="time">@Html.DisplayFor(m => item.ResponseDate)</span></div>
						</div>
						<div class="col reply">@Html.Raw(item.Response)</div>

					</div>
				</div>
			</div>
		</div>
		i++;
	}
}