LeadApp/Models/LeadPhone.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadPhone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeadPhone()
        {
            this.LeadPhoneFollowUps = new HashSet<LeadPhoneFollowUp>();
        }
    
        public int LeadPhoneId { get; set; }
        public Nullable<int> ManufactureId { get; set; }
        public Nullable<int> VehicleYear { get; set; }
        public string VehicleModel { get; set; }
        public string Mileage { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public decimal InitialAmount { get; set; }
        public Nullable<decimal> AmountAccepted { get; set; }
        public string PlaceOfPickup { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsCompleted { get; set; }
        public bool isVarified { get; set; }
        public string Comments { get; set; }
        public string VinNo { get; set; }
        public Nullable<decimal> SalesPrice { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadPhoneFollowUp> LeadPhoneFollowUps { get; set; }
    }
}

LeadApp/Models/LeadPhone/LeadPhoneModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadApp.Models
{



    [MetadataType(typeof(LeadPhoneMetaData))]
	public partial class LeadPhone
	{
        [UIHint("Label4")]
        public string Labelfor { get; set; }
	}

    public class LeadPhoneMetaData
	{
		[Display(Name = "Lead ID")]
		public string LeadPhoneId { get; set; }

		[Display(Name = "Name")]
		[Required]
		//[Remote("isExist", "Lead", AdditionalFields = "LeadId", ErrorMessage = "Lead already exist")]
		[StringLength(100, ErrorMessage = "Must be between 3 and 100 characters", MinimumLength = 3)]
		public string FullName { get; set; }


		[Display(Name = "Phone Number")]
		public string Phone { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Email { get; set; }

        [Display(Name = "Manufacturer")]
        public Nullable<int> ManufactureId { get; set; }

        [Display(Name = "Asking Price")]
        public decimal InitialAmount { get; set; }

     



		
	}
    public class LeadPhoneVM
    {
        public int LeadPhoneId { get; set; }
        public string Manufacturer { get; set; }
        public int? VehicleYear { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string VinNo { get; set; }
        public decimal AskingPrice { get; set; }
       public int? StatusId { get; set; }
       public string Status { get; set; }
     
    }
}

LeadApp/Models/LeadPhone/ProfitLossVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LeadApp.Models
{
    public class ProfitLossVM
    {
        public int LeadPhoneId { get; set; }
        public string Manufacturer { get; set; }
   
        public string Name { get; set; }
        public string Email { get; set; }
   
        public decimal? AmountAccepted { get; set; }
        public decimal? SalesPrice { get; set; }
    
        public string Status { get; set; }
        public DateTime? createdDate { get; set; }

     
    }
}

LeadApp/Models/LeadPhone/VarifyVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LeadApp.Models
{
    public class VarifyVM
    {
        public int LeadPhoneId { get; set; }
        public string Manufacturer { get; set; }

        public string Name { get; set; }
        public string Email { get; set; }

        public decimal? AmountAccepted { get; set; }
        public decimal? SalesPrice { get; set; }
        public string PlaceOfPickups { get; set; }
        public string VehicleModel { get; set; }
        public int? VehicleYear { get; set; }
        public string city { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string VinNo { get; set; }
    }

}

LeadApp/Controllers/LeadPhoneController.cs
using LeadApp.Helpers;
using LeadApp.Models;
using LeadApp.Services;
using System;
using System.Linq.Dynamic;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadApp.Controllers
{
    [Restricted]
    public class LeadPhoneController : Controller
    {
        public ManufacturerService _servMan = new ManufacturerService();
        public LeadPhoneServices _serv = new LeadPhoneServices();
        private LeadAppEntities _context = new LeadAppEntities();
        // GET: LeadPhone
        public ActionResult Detail(int id)
        {

            LeadPhone _data = _serv.Get().Where(e => e.LeadPhoneId == id).FirstOrDefault();
            ViewBag.PendingLeads = _serv.getPendingLeads();
            ViewBag.SubmittedBy = "Submitted by: " + _data.AppUser.UserName;
            ViewBag.LeadPhoneId = id;
            var Lastfollowup = _data.LeadPhoneFollowUps;
            ViewBag.LastFollowUp = Lastfollowup.OrderByDescending(q => q.LeadPhoneFollowUpId);
            var isVarifyButtonVisible = _context.LeadPhones.Where(q => q.isVarified == true && q.LeadPhoneId==id);
            if (isVarifyButtonVisible.Count() > 0)
            {
                ViewBag.IsVarifyButtonVisible = false;
            }
            else
            {
                ViewBag.IsVarifyButtonVisible = true;
            }
            var IsApproveButtonVisible = _context.LeadPhones.Where(q => q.LeadPhoneId == id && q.StatusId == 4);
            if (IsApproveButtonVisible.Count() > 0)
            {
                ViewBag.IsApproveButtonVisible = false;
            }
            else
            {
                ViewBag.IsApproveButtonVisible = true;
            }
            //if(Auth.GroupID==7)
            //{
            //    return RedirectToAction("VarifyLead", new { id = id });
            //}
            if (Auth.GroupID == 5)
            {
                var isSalePriceButtonVisible = _serv.isVisiblePriceButton(id);

                if (isSalePriceButtonVisible == true)
                {
                    ViewBag.isSalePriceButtonVisible = true;
                }
                else
                {
                    ViewBag.isSalePriceButtonVisible = false;
                }
                var IsLeadDisqualifyButtonVisible = _context.LeadPhoneFollowUps.Where(q => q.LeadPhoneId == id);
                if (IsLeadDisqualifyButtonVisible.Count() == 2)
                {
                    ViewBag.IsLeadDisqualifyButtonVisible = true;
                }
                else
                {
                    ViewBag.IsLeadDisqualifyButtonVisible = false;
                }
            }
            else
            {
                ViewBag.IsLeadDisqualifyButtonVisible = false;
            }

            // var _datalastaskingprice = _context.LeadPhoneFollowUps.Where(q => q.LeadPhoneId == id && q.LatestAskingPrice != null).OrderByDescending(q => q.LeadPhoneFollowUpId);
            var _datalastofferedamount = _context.LeadPhoneFollowUps.Where(q => q.LeadPhoneId == id && q.LatestOfferedAmount != null).OrderByDescending(q => q.LeadPhoneFollowUpId);


            // ViewBag.LatestAskingPrice = _datalastaskingprice.Any() ? _datalastaskingprice.FirstOrDefault().LatestAskingPrice : 0;
            ViewBag.LatestOfferedPrice = _datalastofferedamount.Any() ? _datalastofferedamount.FirstOrDefault().LatestOfferedAmount : 0;
            ViewBag.LastFollowUpPrice = Lastfollowup.Any() ? Lastfollowup.OrderByDescending(q => q.LeadPhoneFollowUpId).FirstOrDefault().LatestOfferedAmount : 0;
            if (_data == null)
            {
                TempData["OutputMessage"] = "Record Not Found";
                return RedirectToAction("LeadDetail", new { id = id });
            }
            return View(_data);
        }


        [HttpPost]
        public JsonResult VarifyLead(int id)
        {

            var getVarified = _serv.getVarified(id);
            return Json(getVarified, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult VarifiedLead(int id, string PlaceofPickup, string City, string Phone, string Email, int VehicleYear, string VinNo, string ZipCode)
        {

            var varifiedLead = _serv.VarifiedLead(id, PlaceofPickup, City, Phone, Email, VehicleYear, VinNo, ZipCode);
            return Json(varifiedLead, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create()
        {
            ViewBag.ManufactureId = new SelectList(_servMan.Get(), "ManufactureId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(LeadPhone _data)
        {
            string error = null;
            int LeadPhoneId = 0;
            ViewBag.ManufactureId = new SelectList(_servMan.Get(), "ManufactureId", "Name");
            if (ModelState.IsValid)
            {
                bool isSuccess = _serv.Add(_data, out error, out LeadPhoneId);
                TempData["AlertCSS"] = isSuccess ? "alert success" : "alert error";

                if (!isSuccess)
                    ModelState.AddModelError("", error);

                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Edit(int? id)
        {
            ViewBag.ManufactureId = new SelectList(_servMan.Get(), "ManufactureId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int? id, LeadPhone _data)
        {
            string error = string.Empty;
            ViewBag.ManufactureId = new SelectList(_servMan.Get(), "ManufactureId", "Name");
            if (ModelState.IsValid)
            {
                bool isSuccess = _serv.Edit(id, _data, out error);
                TempData["AlertCSS"] = isSuccess ? "alert success" : "alert error";

                if (!isSuccess)
                    ModelState.AddModelError("", error);
                else
                    TempData["OutputMessage"] = "Record Successfully Modified!";

                if (ModelState.IsValid)
                    return RedirectToAction("Index");
                else
                    return RedirectToAction("Edit", new { id = id });

            }
            return View();
        }

        public ActionResult Index(string q, string isRejected, int? statusid)
        {
            ViewBag.StatusId = statusid;
            ViewBag.PendingLeads = _serv.getPendingLeads();
            //var _data = _serv.GetByUserId(statusid);
            // return Json(new { data = _data }, JsonRequestBehavior.AllowGet);
            return View();
        }
        public ActionResult loadData(int? statusId)
        {
            var _data = _serv.GetByUserId(statusId);
            return Json(new { data = _data }, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public ActionResult Index(int? statusId)
        {
            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
           string searchValue = Request["search[value]"];
            string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            string sortDirection = Request["order[0][dir]"];
            var result = _serv.GetByUserId(statusId);
           
                int totalRows = result.Count();
                if (!String.IsNullOrEmpty(searchValue))
            {
                result = result.Where(x => ((x.Name.ToLower()?? "N/A").Contains(searchValue.ToLower())) ||
                ((x.Status.ToLower()?? "N/A").Contains(searchValue.ToLower())) ||
                ((x.VehicleYear.ToString().ToLower()?? "N/A").Contains(searchValue.ToLower())) ||
               
                ((x.Manufacturer.ToLower()?? "N/A").Contains(searchValue.ToLower())) ||
                x.LeadPhoneId.ToString().ToLower().Contains(searchValue.ToLower()) ||
                ((x.Email.ToLower()?? "N/A").Contains(searchValue.ToLower()))
              ).ToList();
            }
            int totalRowsAfterFilter = result.Count();
            result = result.OrderBy(sortColumnName + " " + sortDirection).ToList();
            result = result.Skip(start).Take(length).ToList();
            return Json(new { data = result, draw = Request["draw"], recordsTotal = totalRows, recordsFiltered = totalRowsAfterFilter }, JsonRequestBehavior.AllowGet);

        }

        

        public ActionResult AddNote(int id, string Note, string Mode, decimal? Amount)
        {
            if (Auth.GroupID == 5)
            {
                var _datalastaskingprice = _context.LeadPhoneFollowUps.Where(q => q.LeadPhoneId == id && q.LatestAskingPrice != null).OrderByDescending(q => q.LeadPhoneFollowUpId);
                if (_datalastaskingprice.Any())
                {
                    var lastasking = _datalastaskingprice.Any() ? _datalastaskingprice.FirstOrDefault().LatestAskingPrice : 0;
                    if (Amount > lastasking)
                    {
                        return Json(4, JsonRequestBehavior.AllowGet);
                    }
                }
            }
            var AddNote = _serv.AddNote(id, Note, Mode, Amount);
            return Json(2, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddNoteOnly(int id, string Note)
        {
            var AddNoteOnly = _serv.AddNoteOnly(id, Note);
            return Json(2, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ApproveLead(int id, string Note, decimal AmountAccepted, string PlaceofPickup, decimal LatestOfferedPrice)
        {
            if (AmountAccepted > LatestOfferedPrice)
            {
                return Json(2, JsonRequestBehavior.AllowGet);
            }

LeadApp/Views/LeadPhone/Edit.cshtml
@model LeadApp.Models.LeadPhone

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>



LeadApp/Views/LeadPhone/Index.cshtml
@model IEnumerable<LeadApp.Models.LeadPhoneVM>

@{

    ViewBag.Title = "Lead";
    ViewBag.CssClass = "no-bg ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (Auth.GroupID == 6)
{
    @section TopBarArea
    {
        <div class="control-bar">@Html.ActionLink("Add Lead", "Create", "LeadPhone", new { @class = "btn btn-primary btn-large wide" })</div>
    }



}
<input type="hidden" value="@ViewBag.StatusId" id="statusId" />
<div class="row">
    <div class="col">
      
        <div class="panel">
            <div class="x_panel">
                <div class="x_title">

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="datatable" class="table">
                        <thead>
                            <tr>

                                <th>
                                    @Html.DisplayNameFor(model => model.LeadPhoneId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Manufacturer)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.VehicleYear)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.VinNo)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.AskingPrice)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>



                                <th></th>
                            </tr>
                        </thead>
                        @*<tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th>
                                            @Html.DisplayFor(model => item.LeadPhoneId)
                                        </th>
                                        <td>
                                            @if (item.Manufacturer != null)
                                            {
                                                @Html.DisplayFor(modelItem => item.Manufacturer.Name)
                                            }

                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.VehicleYear)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.FullName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.InitialAmount)
                                        </td>



                                        <td>

                                            @Html.ActionLink("Details", "Detail", new { id = item.LeadPhoneId })

                                        </td>
                                    </tr>
                                }
                            </tbody>*@
                    </table>
                </div>
            </div>
        </div>


    </div>
</div>

<script type="text/javascript">
   
    function loadData() {
        $('#datatable').dataTable({
            "processing": true,
            "serverSide": true,
            "filter": true,
            "orderMulti": false,
            "ajax": {
                "url": "/LeadPhone/loadData",
                "type": "GET",
                "datatype": "json"

            },
            "columns": [
                  { "data": "LeadPhoneId", "autowidth": true },
                  { "data": "Manufacturer", "autowidth": true },
                  { "data": "VehicleYear", "autowidth": true },
                  { "data": "VinNo", "autowidth": true },
                  { "data": "Name", "autowidth": true },
                  { "data": "Email", "autowidth": true },
                  { "data": "AskingPrice", "autowidth": true },
                     { "data": "Status", "autowidth": true },
                     {
                         "sName": "Details",
                         "bSearchable": false,
                         "bSortable": false,
                         "fnRender": function (oObj) {
                             // oObj.aData[0] returns the RoleId
                             return "<a href='/Details?id="
                                 + oObj.aData[0] + "'>Details</a>";
                         }
                     }
            ]
        });
    }
    function loadPostData(statusid) {
        $('#datatable').dataTable({
          
            "serverSide": true,
            "filter": true,
                "ajax": {
                "url": "/LeadPhone/Index?statusid=" + statusid ,
                "type": "POST",
                "datatype": "json"

            },
            aoColumns: [
                  { "data": "LeadPhoneId","name":"LeadPhoneId", "autowidth": true },
                  { "data": "Manufacturer", "name": "Manufacturer", "autowidth": true },
                  { "data": "VehicleYear", "name": "VehicleYear", "autowidth": true },
                  { "data": "VinNo", "name": "VinNo", "autowidth": true },
                  { "data": "Name", "name": "Name", "autowidth": true },
                  { "data": "Email", "name": "Email", "autowidth": true },
                  { "data": "AskingPrice", "name": "AskingPrice", "autowidth": true },
                    { "data": "Status", "name": "Status", "autowidth": true },
                      {
                          data: null,
                          className: "center",
                          //defaultContent: '<a href="" class="editor_edit">Details</a>',

                          //"sName": "Details",
                          //"bSearchable": false,
                          //"bSortable": false,
                          "mRender": function (oObj) {
                              // oObj.aData[0] returns the RoleId
                              return "<a href='/LeadPhone/Detail?id="
                                  + oObj.LeadPhoneId + "'>Details</a>";
                          }
                      }
            ],
        
            "order": [0, "asc"],
            "processing": true,
            "language": {
            "processing": "Processing....Please Wait"
            }
        });
    }
    $(document).ready(function () {
        var statusid = $("#statusId").val();

        if (statusid == '0') {
            loadData();
        }
        else {


            loadPostData(statusid);
        }

    });




</script>


LeadApp/Views/LeadPhone/Profit_Loss.cshtml
@model IEnumerable<LeadApp.Models.ProfitLossVM>

@{
    ViewBag.Title = "Profit_Loss";
}

<h2>Profit_Loss</h2>

<div style="width:90%;margin:0 auto">
    <div style="width:90%;margin:0 auto">
        <div style="background-color:lightgray;padding:20px">
            <h2>Search Panel</h2>
            <div>
                @using (Html.BeginForm("myaction", "LeadPhone", FormMethod.Get))
                { <div>Start Date:<input type="text" class="sysDateField" name="StartDate" id="StartDate" /></div><br />
                <div>End Date:<input type="text" class="sysDateField" name="EndDate" id="EndDate" /></div><br />
                <div><input type="button" name="btnsubmit" id="btnsubmit" value="Search" /></div><br /><br />

                }
               
            </div>
        </div>
    </div>

</div>
<div class="row">
    <div class="col">

        <div class="panel">
            <div class="x_panel">
                <div class="x_title">

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <table id="ProfitLossTable" class="table">
                        <thead>
                            <tr>

                                <th>
                                    @Html.DisplayNameFor(model => model.LeadPhoneId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Manufacturer)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.AmountAccepted)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.SalesPrice)
                                </th>

                                <th>
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>



                            </tr>
                        </thead>
                        @*<tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th>
                                            @Html.DisplayFor(model => item.LeadPhoneId)
                                        </th>
                                        <td>
                                            @if (item.Manufacturer != null)
                                            {
                                                @Html.DisplayFor(modelItem => item.Manufacturer.Name)
                                            }

                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.VehicleYear)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.FullName)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.InitialAmount)
                                        </td>



                                        <td>

                                            @Html.ActionLink("Details", "Detail", new { id = item.LeadPhoneId })

                                        </td>
                                    </tr>
                                }
                            </tbody>*@
                    </table>
                </div>
            </div>
        </div>


    </div>
</div>
<script>


    $(document).ready(function () {
        $.datepicker.setDefaults({
            dateFormat: "dd M yy"
        });
        $(".sysDateField").datepicker();

        $("#btnsubmit").click(function () {
            $("#ProfitLossTable").dataTable().fnDestroy()
            var startDate = $("#StartDate").val();
            var enddate = $("#EndDate").val();
            $('#ProfitLossTable').dataTable({
                "processing": true,
                "serverSide": true,
                "filter": false,


                "orderMulti": false,

                "ajax": {
                    "url": "/LeadPhone/loadProfitLossData?startdate=" + startDate +"&EndDate="+enddate,
                    "type": "POST",
                    "datatype": "json"

                },

                "aoColumns": [
                      { "data": "LeadPhoneId", "name": "LeadPhoneId", "autowidth": true },
                      { "data": "Manufacturer", "name": "Manufacturer", "autowidth": true },
                      { "data": "Email", "name": "Email", "autowidth": true },
                      { "data": "Name", "name": "Name", "autowidth": true },
                      { "data": "AmountAccepted", "name": "AmountAccepted", "autowidth": true },
                      { "data": "SalesPrice", "name": "SalesPrice", "autowidth": true },
                      { "data": "Status", "name": "Status", "autowidth": true }

                ],
                "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                    if (aData["Status"] == 'Loss') {
                        $('td', nRow).css('background-color', '#f2dede');
                    }
                    else if (aData["Status"] == "Profit") {
                        $('td', nRow).css('background-color', '#dff0d8');
                    }
                    else if (aData["Status"] == 'N/A') {
                        $('td', nRow).css('background-color', 'white');
                    }
                    else {
                        $('td', nRow).css('background-color', '#f2dede');
                    }
                }

            });

            
        });
        $('#ProfitLossTable').dataTable({
            "processing": true,
            "serverSide": true,
            "filter": false,
          

            "orderMulti": false,

            "ajax": {
                "url": "/LeadPhone/loadProfitLossData",
                "type": "POST",
                "datatype": "json"

            },
         
            "aoColumns": [
                  { "data": "LeadPhoneId","name":"LeadPhoneId", "autowidth": true },
                  { "data": "Manufacturer", "name": "Manufacturer", "autowidth": true },
                  { "data": "Email", "name": "Email", "autowidth": true },
                  { "data": "Name", "name": "Name", "autowidth": true },
                  { "data": "AmountAccepted", "name": "AmountAccepted", "autowidth": true },
                  { "data": "SalesPrice", "name": "SalesPrice", "autowidth": true },
                  { "data": "Status", "name": "Status", "autowidth": true }

            ],
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                if (aData["Status"] == 'Loss') {
                    $('td', nRow).css('background-color', '#f2dede');
                }
                else if (aData["Status"] == "Profit") {
                    $('td', nRow).css('background-color', '#dff0d8');
                }
                else if (aData["Status"] == 'N/A') {
                    $('td', nRow).css('background-color', 'white');
                }
                else {
                    $('td', nRow).css('background-color', '#f2dede');
                }
            }

        });

     
    });
</script>